### ISSUE TITLE
Classic Extension Support

### ISSUE THREAD

**Issue by anderlk** [quellenform/t3x-lib-ical-eventnews#1]
Hi,
are there any plans to release the extension and the "[t3x-lib-ical](https://github.com/quellenform/t3x-lib-ical)" Extension as a classic extension (without Composer)?

I would like to use the extension in a system that still runs without Composer?

Thank you, Andreas Keck

**Comment by stephankellermayr** [comment]
@anderlk I actually wanted to do this as soon as the extension is out of beta, but if you think it makes sense now, then I can do it now...

To be honest, I have not yet been able to test the extension to a sufficient extent in different environments, so I would appreciate any feedback and suggestions for improvement.

**Comment by anderlk** [comment]
Hi @stephankellermayr,
thanks for your fast Feedback. If it is out as classic Version in Extension repository, i can do some more testings for you and give Feedback. Many of my projects are actual without composer.

Regards Andreas

**Comment by stephankellermayr** [comment]
OK, it's done. ...but as a reminder: This is a beta version!

https://extensions.typo3.org/extension/lib_ical
https://extensions.typo3.org/extension/lib_ical_eventnews

Thank you for your interest in the extension and your feedback!
